const CONSTANTS = {
    SET_LOADING: "SET_LOADING",
    SET_LOADING_CATEGORIES: "SET_LOADING_CATEGORIES",
    SET_LOADING_PRODUCT: "SET_LOADING_PRODUCT",
    SET_ADDING_PRODUCT: "SET_ADDING_PRODUCT",
    SET_DELETING: "SET_DELETING",

    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",

    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",

    GET_PRODUCT: "GET_PRODUCT",
    GET_PRODUCT_SUCCES: "GET_PRODUCT_SUCCES",
    RESET_PRODUCT_DATA: "RESET_PRODUCT_DATA",
    FILTER_PRODUCTS: "FILTER_PRODUCTS",
    FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",

    GET_CATEGORY: "GET_CATEGORY",
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",


    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",

    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS"

}

export default CONSTANTS